services:
  node:
    build: .
    command: bash -c "cd nextjs-dashboard && npm install && npm run dev"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - 3000:3000
    volumes:
      - .:/app